[workspace]
authors = ["Sierra Arn"]
channels = ["conda-forge"]
name = "finml-lab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.11,<3.13"
ta-lib = ">=0.5.1,<0.6"
jupyter = ">=1.1.1,<2"
pyarrow = ">=21.0.0,<22"
matplotlib = ">=3.10.5,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.1,<2"
optuna = ">=4.4.0,<5"
tqdm = ">=4.67.1,<5"
huggingface_hub = ">=0.34.4,<0.35"

[pypi-dependencies]
torch = ">=2.8.0, <3"
xgboost = ">=3.0.3, <4"
